spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'account-login-manager'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: |
          {{- with secret "'kv/data/account-login-manager/production'" -}}
          {{ .Data.data.mongoString }}
          {{- end -}}